spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://amantripathi7550_db_user:D9L1RpYChCvpBpGj@ai-internship-portal.ftfkc7h.mongodb.net/?appName=ai-internship-portal
spring.data.mongodb.database=internship-portal
server.port=8080